### ISSUE TITLE
mongo importerror: cannot import name get_verbose_name

### ISSUE THREAD

**Issue by makketagg** [jschrewe/django-mongoadmin#33]
Django: 1.7<br>
MongoEngine:  1.8.7<br>

Configuration like a tutorial, but django droped exception...

**Comment by makketagg** [comment]
package is old, need to rename some functions

**Comment by denisvolokh** [comment]
So what is the solution for this issue?

**Comment by autodataming** [comment]
> 
> 
> So what is the solution for this issue?

https://github.com/willhardy/django-seo/issues/48
